import Head from 'next/head';
import { Layout } from '../../components/Layout';

import type { Pokemon } from '../../interfaces/pokemon';

const calculatePower = (pokemon: Pokemon) =>
  pokemon.hp +
  pokemon.attack +
  pokemon.defense +
  pokemon.special_attack +
  pokemon.special_defense +
  pokemon.speed;

const ListPage = ({ pokemons }: { pokemons: Pokemon[] }) => {
  return (
    <>
      <Head>
        <title>Technical test next.js and typescript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Pokemon list</h1>

      <div>
        <div>Search</div>
        <input type="text"></input>
        <div>Power threshold</div>
        <input type="text"></input>
        <div>Count over threshold: </div>
        <div>Min: </div>
        <div>Max: </div>

        <table>
          <thead>
            <tr>
              <th>
              ID
              </th>
              <th>
              Name
              </th>
              <th>
              Type
              </th>
              <th>
              hp
              </th>
              <th>
              Attack
              </th>
              <th>
              Defense
              </th>
              <th>
              Special Attack
              </th>
              <th>
              Special Defense
              </th>
              <th>
              Speed
              </th>
            </tr>
          </thead>
          <tbody>
            {pokemons && pokemons.map(({id, name, type, hp, attack, defense, special_attack, special_defense, speed}) => <tr key={id}>
              <td>
                {id}
              </td>
              <td>
                {name}
              </td>
              <td>
                {type.join(', ')}
              </td>
              <td>
                {hp}
              </td>
              <td>
                {attack}
              </td>
              <td>
                {defense}
              </td>
              <td>
                {special_attack}
              </td>
              <td>
                {special_defense}
              </td>
              <td>
                {speed}
              </td>
            </tr>)}
          </tbody>
        </table>
      </div>
    </>
  );
};

ListPage.getLayout = Layout;

export default ListPage;
