import ListSection from '../apps/list';

import Head from 'next/head';
import { Layout } from '../components/Layout';
import type { Pokemon } from '../interfaces/pokemon';

export async function getServerSideProps() {
  try {
    const pokemons = await fetch('http://localhost:3000/api/pokemons').then(
      (resp) => resp.json()
    );
    return { props: { pokemons } };
  } catch (error) {
    return {
      notFound: true,
    };
  }
}

const HomePage = ({ pokemons }: { pokemons: Pokemon[] }) => {
  return (
    <>
      <Head>
        <title>Technical test next.js and typescript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ListSection pokemons={pokemons} />
    </>
  );
};

HomePage.getLayout = Layout;

export default HomePage;
